### ISSUE TITLE
problem with CopyFilesToVM.psm1

### ISSUE THREAD

**Issue by pierangelo04** [jamesstringerparsec/Easy-GPU-PV#101]
When i start the script i show this error that tell me that the script can't find a file but i don't know  witch it is
<img width="785" alt="Screenshot 2022-01-22 204055" src="https://user-images.githubusercontent.com/84851067/150653212-59810b56-1397-41c4-9bd5-1c6a0a2588a5.png">

if I am wrong to insert this post in the problems sorry I am new on github

**Comment by Blauschleim** [comment]
Had the same error and it got me spend several hours trying to undestand what the error is with making the image bootable. Turns out I always opened the scipt in Powershell ISE (x86), which makes it unable to make the image bootable(It can't run the command bcdboot.exe). So to fix the error open the non-x86 Version of Powershell and follow all the step as provided in the README, then it should work.
![Screenshot 2022-03-13 041627](https://user-images.githubusercontent.com/44347161/158043446-0d732de0-61ef-41c8-9f9f-eb3c01531730.png)
.

**Comment by fillipeags** [comment]
Omg, thanks that saved me a lot of trouble !

**Comment by jamesstringerparsec** [comment]
I added a check for this, for future users
