### ISSUE TITLE
VM software not working properly because "Microsoft driver" shows rather than Nvidia

### ISSUE THREAD

**Issue by scm007** [jamesstringerparsec/Easy-GPU-PV#149]
Inside the Virtual Machine the system doesn't think it has a Nvidia driver. When I open certain applications (Adobe) they complain and error out because they aren't aware of the Nvidia device.

Is it possible to have the driver show has the correct device (RTX 3060 in this case)?

**Comment by Kodikuu** [comment]
The nature of Microsoft's GPU-PV means the exposed device is _not_ actually the real GPU, but as close as possible without truly passing it through. Some applications are specific enough to bump into the rougher edges of that, or try creating contexts on the virtual display device itself (which isn't real hardware) rather than the GPU-PV device. There aren't really any solutions to this, that I'm aware of at least.
