### ISSUE TITLE
Please help !

### ISSUE THREAD

**Issue by bumblebee2511** [jamesstringerparsec/Easy-GPU-PV#178]
Please allow me how to make Easy-GPU-PV
Public can work on windows 7 thanks

**Comment by ADRick-C** [comment]
"Windows 10 20H1+ Pro, Enterprise or Education OR Windows 11 Pro, Enterprise or Education. Windows 11 on host and VM is preferred due to better compatibility."

First if you dont have the above, this script wont help you at all.
Second place, windows 7 does not support HyperVisor in any way. To upgrade your system is the easiest way.
