### ISSUE TITLE
Cs GO crash Faceit pak01_126.vpk

### ISSUE THREAD

**Issue by Ant1Lamer** [jamesstringerparsec/Easy-GPU-PV#208]
So the problem  in faceit play some game and sometime when its loading screen give me this 
![Untitled](https://user-images.githubusercontent.com/49820061/191846473-5c075ea7-0ad0-4226-afdb-946286b57c89.jpg)

Try to verify the game fix for random game and same for now this only in faceit in mm for now not have this problem. Try and something else  but for now im not tested will work. I delete this file and folders materials and models

**Comment by grrminator** [comment]
This may be a CSGo Crash.

However, Parsec's virtual display adapter fucks things up. Please use this instead: https://github.com/grrminator/Easy-GPU-PV

It is an updated and currently working fork

**Comment by Ant1Lamer** [comment]
thanks i cant do this its very hard for me to do. Lets see now after i delete this folder will have changes, if doesnt have i dont know how to make this :D

**Comment by Ant1Lamer** [comment]
Today have update on steam now launch the game and when i choose  what map i play and crash  and give me pak01_153.vpk

**Comment by grrminator** [comment]
I don't think this has something to do with the VM. I'm not sure what is
happening.

**Comment by DJPlaya** [comment]
This isent related to the VM at all and VAC dosent include any countermeasure against virtualization.
Let Steam check your game files and reinstall the game if needed.

You said that you are playing on faceit. I am not sure which security options they have enabled on their servers, but i believe they have sv_pure active which verifies all your texture/model files while connecting/ingame.

Since you said that your game now crashes even when loading a simple map, i would much rather suspect your drive to be a problem. If you are using an HDD, you should verify its integrity with Western Digital Data Lifeguard or Seatools(for Win) for Seagate drives.
