### ISSUE TITLE
nvidia driver error does not support this version of windows

### ISSUE THREAD

**Issue by bobeatsshit** [jamesstringerparsec/Easy-GPU-PV#246]
so i just upgraded my pc to a ryzen 5 5500 (i also have a gtx 1650) when i installed it i can't install the nvidia drivers

**Comment by itsTyrion** [comment]
more info needed

**Comment by bobeatsshit** [comment]
well i followed all the steps that were in the readme but the script didn't install a driver for my gpu and when i installed it my self it said that it isn't compatible with windows

**Comment by itsTyrion** [comment]
As I said, more info is needed.
What driver version? Same Windows build in the VM and the host (check winver)? 
Do you have a screenshot?

**Comment by bobeatsshit** [comment]
my nvidia driver version is 528.24 and here is my windows version:
https://user-images.githubusercontent.com/105605805/217344767-c80c8745-a965-45c6-be48-6e2ff7a15f9a.png
and here is my vm:
https://user-images.githubusercontent.com/105605805/217346807-6c83eea7-586d-4447-a8f6-be9afcda2b8e.png

**Comment by Kodikuu** [comment]
You have two different minor version numbers between your PC and it's VM, please make sure all Windows updates are installed on both, so that they match.

The script _does_ successfully _copy_ your PC's Nvidia drivers into the VM to use. You cannot install graphics drivers in a GPU-PV VM, it uses the host PC's drivers. Attempts to install graphics drivers on a GPU-PV VM may break the VM setup. Graphics driver updates on the host PC likely _will_ break the setup until the script mentioned in the readme is run to update the VM's copy of those drivers.

Windows 11 is the best version of Windows for GPU-PV, as it has improvements for GPU-PV that Windows 10 does not. It also seems as though Windows 10 22H2 in particular may have issues with GPU-PV

**Comment by bobeatsshit** [comment]
i have still one more question i have windows 11 now and reinstalld the vm but nothing is showing up in taskmanager is it supossed to?

**Comment by Kodikuu** [comment]
No, Task Manager will not show a GPU in a GPU-PV VM

**Comment by bobeatsshit** [comment]
is there a way to know if a gpu is passthrough?
