### ISSUE TITLE
GPU-P on nested Virtualization with Linux/KVM Guest and nested Mac OS Guest

### ISSUE THREAD

**Issue by cyberquarks** [jamesstringerparsec/Easy-GPU-PV#26]
This is more of a question than an issue (also maybe a suggestion too) 

I believe Parsec works with Mac OS as host (a certain version?) however this GPU-P solution works with Hyper-V and natively Hyper-V does not support running Mac OS image. Would this solution work with [nested virtualization](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization). Running Arch Linux on Hyper-V with GPU and then KVM with that then from there install Mac OS. [for education purposes]

**Comment by jamesstringerparsec** [comment]
It supports Nested Virtualisation for Intel Win10/11 machines and AMD Win11 machines.  As for the rest of your question...no idea.

**Comment by cyberquarks** [comment]
Hi @jamesstringerparsec yes it's still Windows Host it's the VM inside the Hyper-V (guest) that is Linux.

```
                         ┌────────────────────────┐
                         │    Mac OS VM           │
                         │    (with.Parsec.Host)  │
                         │                        │
┌────────────────────────┼────────────────────────┤
│                        │                        │
│ Hyper-V Guest VM       │      Hyper-V Guest VM  │
│ Windows 11             │      Linux with KVM    │
│ (with Parsec Host)     │                        │
├────────────────────────┴────────────────────────┤
│                                                 │
│ Windows Host in Hyper-V                         │
│                                                 │
│                                                 │
├─────────────────────────────────────────────────┤
│                                                 │
│ Intel CPU with VT-x                             │
│                                                 │
│                                                 │
└─────────────────────────────────────────────────┘
```

With this approach (hopefully) if this can work you can run multiple Mac VM's on same physical machine with GPU enabled so it can run Parsec Host.

**Comment by mikkeyboi** [comment]
> Hi @jamesstringerparsec yes it's still Windows Host it's the VM inside the Hyper-V (guest) that is Linux.
> 
> ```
>                          ┌────────────────────────┐
>                          │    Mac OS VM           │
>                          │    (with.Parsec.Host)  │
>                          │                        │
> ┌────────────────────────┼────────────────────────┤
> │                        │                        │
> │ Hyper-V Guest VM       │      Hyper-V Guest VM  │
> │ Windows 11             │      Linux with KVM    │
> │ (with Parsec Host)     │                        │
> ├────────────────────────┴────────────────────────┤
> │                                                 │
> │ Windows Host in Hyper-V                         │
> │                                                 │
> │                                                 │
> ├─────────────────────────────────────────────────┤
> │                                                 │
> │ Intel CPU with VT-x                             │
> │                                                 │
> │                                                 │
> └─────────────────────────────────────────────────┘
> ```
> 
> With this approach (hopefully) if this can work you can run multiple Mac VM's on same physical machine with GPU enabled so it can run Parsec Host.

Why not try having your KVM as the hypervisor, and then you can have as many macOS VM's (for education purposes) alongside a Windows 11 host with Hyper-V instead? 
So rather than Windows > Linux KVM > macOS, 
you'd have KVM > [(Windows (Hyper-V) > GPU-P funsies ...) macOS | macOS]

It should also be more stable, with lots of documentation from Proxmox, UNRAID, QEMU, etc.

**Comment by pfilipp** [comment]
I think the aim is to have macOS with graphics hardware acceleration(for education purposes ofc) 
@cyberquarks did you try to make it work?

**Comment by cyberquarks** [comment]
> > Hi @jamesstringerparsec yes it's still Windows Host it's the VM inside the Hyper-V (guest) that is Linux.
> > ```
> >                          ┌────────────────────────┐
> >                          │    Mac OS VM           │
> >                          │    (with.Parsec.Host)  │
> >                          │                        │
> > ┌────────────────────────┼────────────────────────┤
> > │                        │                        │
> > │ Hyper-V Guest VM       │      Hyper-V Guest VM  │
> > │ Windows 11             │      Linux with KVM    │
> > │ (with Parsec Host)     │                        │
> > ├────────────────────────┴────────────────────────┤
> > │                                                 │
> > │ Windows Host in Hyper-V                         │
> > │                                                 │
> > │                                                 │
> > ├─────────────────────────────────────────────────┤
> > │                                                 │
> > │ Intel CPU with VT-x                             │
> > │                                                 │
> > │                                                 │
> > └─────────────────────────────────────────────────┘
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With this approach (hopefully) if this can work you can run multiple Mac VM's on same physical machine with GPU enabled so it can run Parsec Host.
> 
> Why not try having your KVM as the hypervisor, and then you can have as many macOS VM's (for education purposes) alongside a Windows 11 host with Hyper-V instead? Seems weird and a driver nightmare going from Windows to Linux to macOS. So rather than Windows (Hyper-V) > Windows (VM) | (Linux KVM > macOS), you'd have KVM > [(Windows (Hyper-V) > GPU-P funsies ...) macOS | macOS]
> 
> It should also be more stable, with lots of documentation from Proxmox, UNRAID, QEMU, etc.

Are you referring to dual-boot Linux (host) and Windows (host)?

**Comment by mikkeyboi** [comment]
> Are you referring to dual-boot Linux (host) and Windows (host)?

No, Linux KVM is the hypervisor. From there, you spin up as many VMs as you want, including Windows with Hyper-V or macOS with GPU passthrough.

**Comment by Daasin** [comment]
> > 
> 
> No, Linux KVM (host) is the hypervisor. From there, you spin up as many VMs as you want, including Windows with Hyper-V (passthrough) **_`**_or macOS with GPU passthrough (educational purposes)._**`_** Or an ESXi host as the hypervisor, and Windows VM with Hyper-V passthrough. Having nested hypervisors aren't uncommon, 

or I mean shouldn't it be fine if working on supported intel mac hardware? it's not like they haven't got WIP Linux Hypervisors running on that _re: Asahi Linux_

**Comment by mikkeyboi** [comment]
> or I mean shouldn't it be fine if working on supported intel mac hardware? it's not like they haven't got WIP Linux Hypervisors running on that _re: Asahi Linux_

You'll need to clarify what "supported intel mac hardware" means, because yes it is fine if you are running all of this on an Apple logic board, but it's not fine running a custom setup with the same CPU as one found in a Mac Pro even if it works. Hence the "educational purposes" being said, without delving into the hardware of OP.

If you've setup a hypervisor (KVM or ESXi) on a Mac and passed through all the hardware into the macOS VM without any spoofing then it can be arguably supported. 

Also, I'm not sure what you mean by mentioning Asahi Linux, that's a potential bootloader to push Linux integration with Apple ARM silica. It's irrelevant in this repo because Hyper-V isn't supported on Apple ARM hardware (Apple cannot license M1 Windows support until the Microsoft-Qualcomm partnership ends), and OP has an Intel CPU. If you're suggesting that you can get a macOS VM on Apple Silica booted on Asahi Linux, yes that works.

This is probably going to get derailed further. You might want to add some labels or indicator for a POC otherwise this isn't an issue.

@cyberquarks you should re-clarify if you want GPU-P on macOS with GPU hardware acceleration. For your schematic, the most you'd get is software accelerated graphics, and I've typed my suggestions on how you can get GPU acceleration on a macOS VM above. If you're still going to pursue your schematic, let us know here if you're able to GPU-P a Linux VM in Hyper-V, and how viable the Linux VM is. Then we can see how to make the Linux VM into a headless KVM....

**Comment by eudy97** [comment]
Please reopen; this issue remains unresolved.

PS C:\WINDOWS\system32> C:\Easy-GPU-PV-main\CopyFilesToVM.ps1                                                                                                                                                                                   Security warning                                                                                                        
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\Easy-GPU-PV-main\Add-VMGpuPartitionAdapterFiles.psm1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): r

Windows(R) Image to Virtual Hard Disk Converter for Windows(R) 10
Copyright (C) Microsoft Corporation.  All rights reserved.
Version 10.0.14278.1000.amd64fre.rs1_es_media.160201-1707

INFO   : Opening ISO Win11_24H2_English_x64.iso...
INFO   : Looking for F:\sources\install.wim...
INFO   : Looking for the requested Windows image in the WIM file
INFO   : Image 6 selected (Professional)...
INFO   : Creating sparse disk...
INFO   : Mounting VHDX...
INFO   : Initializing disk...
INFO   : Creating EFI system partition...
INFO   : Formatting system volume...
INFO   : Setting system partition as ESP...
INFO   : Creating MSR partition...
INFO   : Creating windows partition...
INFO   : Formatting windows volume...
INFO   : Windows path (H:) has been assigned.
INFO   : Windows path (H:) took 1 attempts to be assigned.
INFO   : System volume location: G:
INFO   : Applying image to VHDX. This could take a while...
INFO   : Image was applied successfully.
INFO   : Applying unattend file (autounattend.xml)...
INFO   : Making image bootable...
INFO   : Drive is bootable.  Cleaning up...
INFO   : Finding and copying driver files for NVIDIA GeForce RTX 5080 to VM. This could take a while...
INFO   : Setting up Parsec to install at boot
INFO   : Dismounting VHDX...
INFO   : Closing Windows image...
INFO   : Done.
INFO   : Starting and connecting to VM
Start-VM : 'RPC01' failed to start.
'RPC01' could not initialize.
The virtual machine could not be started because this platform does not support nested virtualization.
'RPC01' failed to start. (Virtual machine ID 7AF7F101-E926-48DE-8F7D-6C954FEB3666)
'RPC01' failed to start worker process: Unspecified error (0x80004005). (Virtual machine ID
7AF7F101-E926-48DE-8F7D-6C954FEB3666)
'RPC01' could not initialize. (Virtual machine ID 7AF7F101-E926-48DE-8F7D-6C954FEB3666)
The virtual machine could not be started because this platform does not support nested virtualization. Consider not
exposing virtualization extensions to the virtual machine.
At C:\Easy-GPU-PV-main\CopyFilesToVM.ps1:4400 char:1
+ Start-VM -Name $params.VMName
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.StartVM

If all went well the Virtual Machine will have started,
In a few minutes it will load the Windows desktop,
when it does, sign into Parsec (a fast remote desktop app)
and connect to the machine using Parsec from another computer.
Have fun!
Sign up to Parsec at https://parsec.app/
Press any key to Exit...:
