### ISSUE TITLE
Trouble getting minecraft to work

### ISSUE THREAD

**Issue by YourRentIsDue** [jamesstringerparsec/Easy-GPU-PV#74]
Gives me a GLFW 65542 error. I tried installing the compatability package off the store linked in the readme, that didn't work. Am I shit out of luck or are there other things I can try?

**Comment by Aydinator91** [comment]
Same need help cs go also crashes

**Comment by kobimx** [comment]
As discussed in this issue https://github.com/jamesstringerparsec/Easy-GPU-PV/issues/44#issuecomment-1010171541 OpenGl apps can work but theres some caveats

You need to install this [OpenCL™ and OpenGL® Compatibility Pack](https://www.microsoft.com/en-us/p/opencl-and-opengl-compatibility-pack/9nqpsl29bfff?SilentAuth=1&wa=wsignin1.0#activetab=pivot:overviewtab) from the Microsoft store on the VM and also enable the Hyper-V display adapter in device manager
But beware that by doing so you will have a performance hit since the Hyper-V display adapter is not good and and because Parsec will connect and use the display generated by the Hyper-V display adapter and not Parsec-VDD losing all the custom resolutions presented by Parsec, capping at 1080p with worst performance

Here's how i made it work on my setup, it should work but i have no guaranties
FYI: My host and guest are both running Windows 11
- Connect to the VM using RDP locally to perform these operations
- Delete the custom startup scripts present in `\Windows\system32\GroupPolicy`, see here https://github.com/jamesstringerparsec/Easy-GPU-PV/blob/0d41cdfbd53bfbe7c190813f147992fa83479f81/CopyFilesToVM.ps1#L164
- Edit the Parsec config file, commenting out the last 2 lines (you could technically also just set them to 0 but i haven't tried it) aka `host_virtual_monitors = 1` and `host_privacy_mode = 1`
- Enable the Hyper-V display adapter
- Reboot
- Disconnect the RDP session before che VM starts up

After that try connecting through Parsec, without opening a RPD session, and launch minecraft

It's a hack but it works well enough for my use case

**Comment by YourRentIsDue** [comment]
Thanks brother, I'll try that.

**Comment by grrminator** [comment]
https://github.com/grrminator/Easy-GPU-PV

Try this. I dont mean to plug. But Parsec's Virtual Display adapter fucks everything up. This will work if you follow ALL of the instruction steps.
